version: '3'

services:
  nginx:
    container_name: $CONTAINER_NAME-nginx
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "$NGINX_OUTER_PORT:80"
  user-service:
    container_name: $CONTAINER_NAME-user-service
    restart: always
    build:
      context: ./user-service
      target: dependencies
    ports:
      - $USER_SERVICE_API_OUTER_PORT:3333
    env_file:
      - .env.user-service
    volumes:
      - ./user-service:/home/node/app
      # Uncomment the below line if you developing on MacOS
      - /home/node/app/node_modules
    command: dumb-init node ace serve --watch --node-args="--inspect=0.0.0.0"
  post-service:
    container_name: $CONTAINER_NAME-post-service
    restart: always
    build:
      context: ./post-service
      target: dependencies
    ports:
      - $POST_SERVICE_API_OUTER_PORT:4444
    env_file:
      - .env.post-service
    volumes:
      - ./post-service:/home/node/app
      # Uncomment the below line if you developing on MacOS
      - /home/node/app/node_modules
    command: dumb-init node ace serve --watch --node-args="--inspect=0.0.0.0"